### ISSUE TITLE
Loghi in "Chi siamo"

### ISSUE THREAD

**Issue by rossimail** [ondata/opendatagiustizia-contest#3]
![colab](https://cloud.githubusercontent.com/assets/20797046/17333136/6bd70140-58d1-11e6-8fad-ec82d0bf7c10.jpg)
Nel "chi siamo" inserirei i loghi di CO.LAB e ONDATA, eventualmente anche di ADG

**Comment by nelsonmau** [comment]
@ariannatoniolo e @giuragu ho sistemato i loghi in basso, date un'occhiata pls? è tutto online su opendatagiustizia.it
gracias :)

**Comment by giuragu** [comment]
@nelsonmau Ok. Solo un'osservazione. La sezione contatti credo fosse stata tolta giorni fa da @ariannatoniolo essendo duplicato di "contattaci" in basso.  Se confermate la toglierei.

**Comment by ariannatoniolo** [comment]
confermo

## 

Arianna Toniolo

mob 3405726391
Skype Arianna Toniolo

2016-08-04 9:30 GMT+02:00 Giuseppe Ragusa notifications@github.com:

**Comment by giuragu** [comment]
Perfetto. Ho eliminato la sezione contatti.

**Comment by aborruso** [comment]
@giuragu io la vedo ancora online.

**Comment by ariannatoniolo** [comment]
io non la vedo più

## 

Arianna Toniolo

mob 3405726391
Skype Arianna Toniolo

2016-08-04 11:55 GMT+02:00 Andrea Borruso notifications@github.com:

**Comment by giuragu** [comment]
@aborruso parlavamo di questa sezione. Neanch'io la vedo più
![sezione contatti](https://cloud.githubusercontent.com/assets/12112056/17398025/ffecba90-5a3a-11e6-969c-8fe01ae8d3de.png)

**Comment by aborruso** [comment]
@giuragu non avevo capito nulla, pensavo parlaste di "chi siamo" e "contatti" che mi sembravano doppioni e che in realtà non lo sono.

Scusatemi

**Comment by giuragu** [comment]
@aborruso ma di che? no problem!

**Comment by ariannatoniolo** [comment]
ragazzi il mio capo chiede di fare i 3 loghi tutti della stessa grandezza,
poi smettiamo di rompere

## 

Arianna Toniolo

mob 3405726391
Skype Arianna Toniolo

2016-08-04 12:11 GMT+02:00 Giuseppe Ragusa notifications@github.com:

**Comment by giuragu** [comment]
Buongiorno @ariannatoniolo. Ho cercato di rendere i loghi della stessa grandezza come da tue indicazioni. Puoi verificare se va bene così? Non preoccuparti, se non vanno bene puoi dire pure, non rompete affatto :)

**Comment by ariannatoniolo** [comment]
direi ok. grazie

## 

Arianna Toniolo

mob 3405726391
Skype Arianna Toniolo

2016-08-05 10:22 GMT+02:00 Giuseppe Ragusa notifications@github.com:

**Comment by nelsonmau** [comment]
se una cosa è ok, si può poi commentare e "chiudere" la issue, come faccio ora io :)
