### ISSUE TITLE
"contatti"

### ISSUE THREAD

**Issue by rossimail** [ondata/opendatagiustizia-contest#4]
Il tasto "contatti" in alto a destra non funziona

**Comment by giuragu** [comment]
Salve @rossimail.
Credo di aver risolto. Adesso dovrebbe funzionare.

**Comment by rossimail** [comment]
Ottimo, perfetto 

Da: Giuseppe Ragusa notifications@github.com
Risposta: ondata/opendatagiustizia-contest reply@reply.github.com
Data: mercoledì 3 agosto 2016 17:05
A: ondata/opendatagiustizia-contest opendatagiustizia-contest@noreply.github.com
Cc: Simone Rossi simone.rossi@ltdfr.it, Mention mention@noreply.github.com
Oggetto: Re: [ondata/opendatagiustizia-contest] "contatti" (#4)

Salve @rossimail.
Credo di aver risolto. Adesso dovrebbe funzionare.


