### ISSUE TITLE
Fare pagina FAQ

### ISSUE THREAD

**Issue by nelsonmau** [ondata/opendatagiustizia-contest#6]

**Comment by giuragu** [comment]
Buongiorno, rieccoci!
@nelsonmau @ariannatoniolo ho creato in draft una pagina [faq](http://opendatagiustizia.it/faq) (in home page non ho ancora inserito apposito link in menu).
Sarei comunque per decidere se proseguire con la pagina proposta sopra o inserire tutto direttamente in home page a seguire.
Inoltre che ne dite di aprire un gdoc per raccogliere le faq?

**Comment by ariannatoniolo** [comment]
Ottimo, volevo farlo io oggi ma tra le riunioni sono un po'affogata. 
Se riesci tu, ti devo un caffè 

Envoyé de mon iPhone
