### ISSUE TITLE
Problemi di accesso 

### ISSUE THREAD

**Issue by fedaccia** [ondata/opendatagiustizia-contest#8]
remote: Permission to ondata/opendatagiustizia-contest.git denied to fedaccia.
fatal: unable to access 'https://github.com/ondata/opendatagiustizia-contest.git/': The requested URL returned error: 403

**Comment by nelsonmau** [comment]
@fedaccia se vai qui da loggata in github dovresti vedere un invito ad accedere per te https://github.com/ondata/opendatagiustizia-contest/invitations

**Comment by nelsonmau** [comment]
risolto
